/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: "lf",
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@/components/layouts/(.*)$",
    "^@/components/pages/(.*)$",
    "^@/components/forms/(.*)$",
    "^@/components/elements/(.*)$",
    "^@/components/(.*)$",
    "^@/styles/(.*)$",
    "^@/app/(.*)$",
    "",
    "^types$",
    "^@/types/(.*)$",
    "",
    "^@/dict/(.*)$",
    "",
    "^@/hooks/(.*)$",
    "^@/core/(.*)$",
    "^@/middlewares/(.*)$",
    "^@/lib/(.*)$",
    "^@/(.*)$",
    "",
    "^#/(.*)$",
    "",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
};
